create table if not exists sessions (
  id uuid primary key,
  title text not null,
  started_at timestamptz not null,
  ended_at timestamptz,
  active boolean not null default true
);

create table if not exists items (
  id uuid primary key,
  captured_at timestamptz not null,
  session_id uuid not null references sessions(id) on delete cascade,
  name text,
  base_type text not null,
  quality text not null,
  item_level integer not null default 0,
  location text not null,
  defense integer,
  quantity integer,
  display_name text not null,
  is_corrupted boolean not null default false,
  icon_key text,
  category text not null default 'misc',
  analysis_profile text not null default 'unknown',
  analysis_tags jsonb not null default '[]',
  raw_json text not null,
  fingerprint text not null
);

create table if not exists item_stats (
  id bigint generated by default as identity primary key,
  item_id uuid not null references items(id) on delete cascade,
  stat_name text not null,
  stat_value double precision,
  range_min double precision,
  range_max double precision,
  stat_id integer,
  corrupted boolean not null default false
);

create table if not exists settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null
);

create index if not exists idx_items_captured_at on items (captured_at desc);
create index if not exists idx_items_session_id on items (session_id);
create index if not exists idx_items_fingerprint_captured on items (fingerprint, captured_at desc);
